# Generated by Django 4.0.4 on 2022-05-02 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homepageBolgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=800000)),
                ('img', models.ImageField(upload_to='HomeBlog/')),
                ('keyWord', models.TextField(blank=True, max_length=80000)),
                ('title', models.TextField(max_length=80000)),
                ('dateUploaded', models.DateTimeField(auto_now=True)),
                ('author', models.TextField(blank=True, default='none', max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='imgLIst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgname', models.TextField()),
                ('imgs', models.ImageField(upload_to='imglist/')),
                ('imggroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.homepagebolgs')),
            ],
        ),
    ]
