# Generated by Django 4.0.4 on 2022-05-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=8000)),
                ('content', models.TextField(blank=True, max_length=5000000)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='imglist',
            name='imggroup',
        ),
        migrations.DeleteModel(
            name='homepageBolgs',
        ),
        migrations.DeleteModel(
            name='imgLIst',
        ),
    ]
